export const FETCH_MOVIE_BY_ID = 'FETCH_MOVIE_BY_ID';
export const FETCH_MOVIE_BY_ID_SUCCESS = 'FETCH_MOVIE_BY_ID_SUCCESS';
export const FETCH_MOVIE_BY_ID_FAILE = 'FETCH_MOVIE_BY_ID_FAILE';

// info bookAble
export const GET_BOOKING_ABLE = 'GET_BOOKING_ABLE';
export const GET_BOOKING_ABLE_SUCCSESS = 'GET_BOOKING_ABLE_SUCCSESS';
export const GET_BOOKING_ABLE_FAILE = 'GET_BOOKING_ABLE_FAILE';
