export const UPDATE_PROFILE_USER = 'UPDATE_PROFILE_USER';
export const UPDATE_PROFILE_USER_SUCCESS = 'UPDATE_PROFILE_USER_SUCCESS';
export const UPDATE_PROFILE_USER_FAILE = 'UPDATE_PROFILE_USER_FAILE';
