export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILE = 'FETCH_USER_FAILE';

// Feature movie action

export const FETCH_FEATURE_MOVIE = 'FETCH_FEATURE_MOVIE';
export const FETCH_FEATURE_MOVIE_SUCCESS = 'FETCH_FEATURE_MOVIE_SUCCESS';
export const FETCH_FEATURE_MOVIE_FAILE = 'FETCH_FEATURE_MOVIE_FAILE';
