export const FETCH_FEATURE_MOVIE = 'FETCH_FEATURE_MOVIE';
export const FETCH_FEATURE_MOVIE_SUCCESS = 'FETCH_FEATURE_MOVIE_SUCCESS';
export const FETCH_FEATURE_MOVIE_FAILE = 'FETCH_FEATURE_MOVIE_FAILE';
